// Copyright (c) Microsoft. All rights reserved.

using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.Agents.AI.Hosting.OpenAI.Responses.Models;

namespace Microsoft.Agents.AI.Hosting.OpenAI.Responses;

[JsonSourceGenerationOptions(JsonSerializerDefaults.Web,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        NumberHandling = JsonNumberHandling.AllowReadingFromString,
        AllowOutOfOrderMetadataProperties = true,
        WriteIndented = false)]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(CreateResponse))]
[JsonSerializable(typeof(Response))]
[JsonSerializable(typeof(StreamingResponseEvent))]
[JsonSerializable(typeof(StreamingResponseCreated))]
[JsonSerializable(typeof(StreamingResponseInProgress))]
[JsonSerializable(typeof(StreamingResponseCompleted))]
[JsonSerializable(typeof(StreamingResponseIncomplete))]
[JsonSerializable(typeof(StreamingResponseFailed))]
[JsonSerializable(typeof(StreamingOutputItemAdded))]
[JsonSerializable(typeof(StreamingOutputItemDone))]
[JsonSerializable(typeof(StreamingContentPartAdded))]
[JsonSerializable(typeof(StreamingContentPartDone))]
[JsonSerializable(typeof(StreamingOutputTextDelta))]
[JsonSerializable(typeof(StreamingOutputTextDone))]
[JsonSerializable(typeof(StreamingFunctionCallArgumentsDelta))]
[JsonSerializable(typeof(StreamingFunctionCallArgumentsDone))]
[JsonSerializable(typeof(ReasoningOptions))]
[JsonSerializable(typeof(ResponseUsage))]
[JsonSerializable(typeof(ResponseError))]
[JsonSerializable(typeof(IncompleteDetails))]
[JsonSerializable(typeof(InputTokensDetails))]
[JsonSerializable(typeof(OutputTokensDetails))]
[JsonSerializable(typeof(ConversationReference))]
[JsonSerializable(typeof(ResponseInput))]
[JsonSerializable(typeof(InputMessage))]
[JsonSerializable(typeof(List<InputMessage>))]
[JsonSerializable(typeof(IReadOnlyList<InputMessage>))]
[JsonSerializable(typeof(InputMessageContent))]
[JsonSerializable(typeof(ResponseStatus))]
[JsonSerializable(typeof(List<ItemContent>))]
[JsonSerializable(typeof(IList<ItemContent>))]
[JsonSerializable(typeof(ItemResource))]
[JsonSerializable(typeof(ResponsesMessageItemResource))]
[JsonSerializable(typeof(ResponsesAssistantMessageItemResource))]
[JsonSerializable(typeof(ResponsesUserMessageItemResource))]
[JsonSerializable(typeof(ResponsesSystemMessageItemResource))]
[JsonSerializable(typeof(ResponsesDeveloperMessageItemResource))]
[JsonSerializable(typeof(FileSearchToolCallItemResource))]
[JsonSerializable(typeof(FunctionToolCallItemResource))]
[JsonSerializable(typeof(FunctionToolCallOutputItemResource))]
[JsonSerializable(typeof(ComputerToolCallItemResource))]
[JsonSerializable(typeof(ComputerToolCallOutputItemResource))]
[JsonSerializable(typeof(WebSearchToolCallItemResource))]
[JsonSerializable(typeof(ReasoningItemResource))]
[JsonSerializable(typeof(ItemReferenceItemResource))]
[JsonSerializable(typeof(ImageGenerationToolCallItemResource))]
[JsonSerializable(typeof(CodeInterpreterToolCallItemResource))]
[JsonSerializable(typeof(LocalShellToolCallItemResource))]
[JsonSerializable(typeof(LocalShellToolCallOutputItemResource))]
[JsonSerializable(typeof(MCPListToolsItemResource))]
[JsonSerializable(typeof(MCPApprovalRequestItemResource))]
[JsonSerializable(typeof(MCPApprovalResponseItemResource))]
[JsonSerializable(typeof(MCPCallItemResource))]
[JsonSerializable(typeof(IList<ItemResource>))]
[JsonSerializable(typeof(List<ItemResource>))]
[JsonSerializable(typeof(ItemContent))]
[JsonSerializable(typeof(ItemContentInputText))]
[JsonSerializable(typeof(ItemContentInputAudio))]
[JsonSerializable(typeof(ItemContentInputImage))]
[JsonSerializable(typeof(ItemContentInputFile))]
[JsonSerializable(typeof(ItemContentOutputText))]
[JsonSerializable(typeof(ItemContentOutputAudio))]
[JsonSerializable(typeof(ItemContentRefusal))]
[JsonSerializable(typeof(TextConfiguration))]
[JsonSerializable(typeof(ResponseTextFormatConfiguration))]
[JsonSerializable(typeof(ResponseTextFormatConfigurationText))]
[JsonSerializable(typeof(ResponseTextFormatConfigurationJsonObject))]
[JsonSerializable(typeof(ResponseTextFormatConfigurationJsonSchema))]
[ExcludeFromCodeCoverage]
internal sealed partial class ResponsesJsonContext : JsonSerializerContext;
