// Copyright (c) Microsoft. All rights reserved.

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.Extensions.AI;
using Microsoft.Shared.Diagnostics;

namespace Microsoft.Agents;

/// <summary>
/// Optional parameters when running an agent.
/// </summary>
public class AgentRunOptions
{
    /// <summary>
    /// Initializes a new instance of the <see cref="AgentRunOptions"/> class.
    /// </summary>
    public AgentRunOptions()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="AgentRunOptions"/> class by cloning the provided options.
    /// </summary>
    /// <param name="options">The options to clone.</param>
    public AgentRunOptions(AgentRunOptions options)
    {
        Throw.IfNull(options);
        this.OnIntermediateMessages = options.OnIntermediateMessages;
    }

    /// <summary>
    /// Gets or sets a function to be called when a complete new message is generated by the agent.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This callback is particularly useful in cases where the caller wants to receive complete messages
    /// when invoking the agent with streaming.
    /// </para>
    /// </remarks>
    public Func<IReadOnlyCollection<ChatMessage>, Task>? OnIntermediateMessages { get; set; } = null;
}
