dirs:
  - .
excludedFiles:
  - ./python/CHANGELOG.md
ignorePatterns:
  - pattern: "/github/"
  - pattern: "./actions"
  - pattern: "./blob"
  - pattern: "./issues"
  - pattern: "./discussions"
  - pattern: "./pulls"
  - pattern: "https:\/\/platform.openai.com"
  - pattern: "http:\/\/localhost"
  - pattern: "http:\/\/127.0.0.1"
  - pattern: "https:\/\/localhost"
  - pattern: "https:\/\/127.0.0.1"
  - pattern: "0001-spec.md"
  - pattern: "0001-madr-architecture-decisions.md"
  - pattern: "https://api.powerplatform.com/.default"
  - pattern: "https://your-resource.openai.azure.com/"
  - pattern: "http://host.docker.internal"
  - pattern: "https://openai.github.io/openai-agents-js/openai/agents/classes/"
# excludedDirs:
  # Folders which include links to localhost, since it's not ignored with regular expressions
baseUrl: https://github.com/microsoft/agent-framework/
aliveStatusCodes:
  - 200
  - 206
  - 429
  - 500
  - 503
useGitIgnore: true
