<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Microsoft.Agents.AI.OpenAI\Microsoft.Agents.AI.OpenAI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.OpenAI" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\FeatureUsageAssert.cs" Link="FeatureUsageAssert.cs" />
    <ProjectReference Include="..\..\src\Microsoft.Agents.AI.Abstractions\Microsoft.Agents.AI.Abstractions.csproj" />
    <Using Include="Microsoft.Agents.AI.Testing" />
  </ItemGroup>

</Project>
