// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Microsoft.Agents.AI.Workflows.Declarative.CodeGen
{
    using System.Collections.Generic;
    using Microsoft.Agents.ObjectModel;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    internal partial class ClearAllVariablesTemplate : ActionTemplate
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n/// <summary>\n/// Reset all the state for the targeted variable scope.\n/// </sum" +
                    "mary>\ninternal sealed class ");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Name));
            this.Write("Executor(FormulaSession session) : ActionExecutor(id: \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Id));
            this.Write("\", session)\n{\n    // <inheritdoc />\n    protected override async ValueTask<object" +
                    "?> ExecuteAsync(IWorkflowContext context, CancellationToken cancellationToken)\n " +
                    "   {");

        EvaluateEnumExpression<VariablesToClearWrapper, string>(this.Model.Variables, "targetScopeName", ScopeMap, isNullable: true); 
            this.Write("\n        await context.QueueClearScopeAsync(targetScopeName).ConfigureAwait(false" +
                    ");\n\n        return default;\n    }\n}\n");
            return this.GenerationEnvironment.ToString();
        }

void AssignVariable(PropertyPath targetVariable, string valueVariable, bool tightFormat = false)
{
    if (targetVariable is not null)
    {
this.Write("\n        await context.QueueStateUpdateAsync(key: \"");

this.Write(this.ToStringHelper.ToStringWithCulture(VariableName(targetVariable)));

this.Write("\", value: ");

this.Write(this.ToStringHelper.ToStringWithCulture(valueVariable));

this.Write(", scopeName: \"");

this.Write(this.ToStringHelper.ToStringWithCulture(VariableScope(targetVariable)));

this.Write("\").ConfigureAwait(false);");


        if (!tightFormat)
        {
this.Write("\n        ");

}
    }
}


void EvaluateEnumExpression<TWrapper, TValue>(
    EnumExpression<TWrapper> expression, 
    string targetVariable,
    IDictionary<TWrapper, string> resultMap,
    string defaultValue = null,
    bool qualifyResult = false,
    bool isNullable = false)
        where TWrapper : EnumWrapper
{
    string resultType = $"{GetTypeAlias<TValue>()}{(isNullable ? "?" : "")}";
    if (expression is null)
    {
this.Write("\n        ");

this.Write(this.ToStringHelper.ToStringWithCulture(resultType));

this.Write(" ");

this.Write(this.ToStringHelper.ToStringWithCulture(targetVariable));

this.Write(" = ");

this.Write(this.ToStringHelper.ToStringWithCulture(FormatValue<TValue>(defaultValue)));

this.Write(";");

 
    }
    else if (expression.IsLiteral)
    { 
        resultMap.TryGetValue(expression.LiteralValue, out string resultValue);
        if (qualifyResult)
        {
this.Write("\n        ");

this.Write(this.ToStringHelper.ToStringWithCulture(resultType));

this.Write(" ");

this.Write(this.ToStringHelper.ToStringWithCulture(targetVariable));

this.Write(" = ");

this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeAlias<TValue>()));

this.Write(".");

this.Write(this.ToStringHelper.ToStringWithCulture(resultValue));

this.Write(";");

 
        }
        else
        {
this.Write("\n        ");

this.Write(this.ToStringHelper.ToStringWithCulture(resultType));

this.Write(" ");

this.Write(this.ToStringHelper.ToStringWithCulture(targetVariable));

this.Write(" = ");

this.Write(this.ToStringHelper.ToStringWithCulture(FormatValue<TValue>(resultValue)));

this.Write(";");

 
        }
    }
    else if (expression.IsVariableReference && expression.VariableReference.SegmentCount == 2)
    {
this.Write("\n        ");

this.Write(this.ToStringHelper.ToStringWithCulture(resultType));

this.Write(" ");

this.Write(this.ToStringHelper.ToStringWithCulture(targetVariable));

this.Write(" = await context.ReadStateAsync<");

this.Write(this.ToStringHelper.ToStringWithCulture(resultType));

this.Write(">(key: \"");

this.Write(this.ToStringHelper.ToStringWithCulture(expression.VariableReference.VariableName));

this.Write("\", scopeName: \"");

this.Write(this.ToStringHelper.ToStringWithCulture(expression.VariableReference.NamespaceAlias));

this.Write("\").ConfigureAwait(false);");


    }
    else if (expression.IsVariableReference)
    {
this.Write("\n        ");

this.Write(this.ToStringHelper.ToStringWithCulture(resultType));

this.Write("? ");

this.Write(this.ToStringHelper.ToStringWithCulture(targetVariable));

this.Write(" = await context.EvaluateValueAsync<");

this.Write(this.ToStringHelper.ToStringWithCulture(resultType));

this.Write(">(");

this.Write(this.ToStringHelper.ToStringWithCulture(FormatStringValue(expression.VariableReference.ToString())));

this.Write(").ConfigureAwait(false);");

 
    }
    else
    {
this.Write("\n        ");

this.Write(this.ToStringHelper.ToStringWithCulture(resultType));

this.Write(" ");

this.Write(this.ToStringHelper.ToStringWithCulture(targetVariable));

this.Write(" = await context.EvaluateValueAsync<");

this.Write(this.ToStringHelper.ToStringWithCulture(resultType));

this.Write(">(");

this.Write(this.ToStringHelper.ToStringWithCulture(FormatStringValue(expression.ExpressionText)));

this.Write(").ConfigureAwait(false);");

 
    }
}

    }
}
