// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Microsoft.Agents.AI.Workflows.Declarative.CodeGen
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    internal partial class EdgeTemplate : CodeTemplate
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\n");
            this.Write("\n");
 if (this.Condition is not null)
{
            this.Write("\n    builder.AddEdge(");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.SourceId));
            this.Write(", ");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TargetId));
            this.Write(", (object? result) => ");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Condition));
            this.Write(");");

}
else
{
            this.Write("\n    builder.AddEdge(");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.SourceId));
            this.Write(", ");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TargetId));
            this.Write(");");

} 
            this.Write("\n");
            return this.GenerationEnvironment.ToString();
        }
    }
}
