// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Microsoft.Agents.AI.Workflows.Declarative.CodeGen
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    internal partial class InstanceTemplate : CodeTemplate
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\n");
            this.Write("\n");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ExecutorType));
            this.Write("Executor ");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.InstanceVariable));
            this.Write(" = new(");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.RootVariable));
            this.Write(".Session");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.HasProvider ? ", options.AgentProvider" : ""));
            this.Write(");");
            return this.GenerationEnvironment.ToString();
        }
    }
}
