// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Microsoft.Agents.AI.Workflows.Declarative.CodeGen
{
    using Microsoft.Agents.AI.Workflows.Declarative.Extensions;
    using Microsoft.Agents.ObjectModel;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    internal partial class SendActivityTemplate : ActionTemplate
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n/// <summary>\n/// Formats a message template and sends an activity event.\n/// </" +
                    "summary>\ninternal sealed class ");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Name));
            this.Write("Executor(FormulaSession session) : ActionExecutor(id: \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Id));
            this.Write("\", session)\n{\n    // <inheritdoc />\n    protected override async ValueTask<object" +
                    "?> ExecuteAsync(IWorkflowContext context, CancellationToken cancellationToken)\n " +
                    "   { ");

if (this.Model.Activity is MessageActivityTemplate messageActivity)
{ 
            this.Write("\n        string activityText = \n            await context.FormatTemplateAsync( ");

    foreach (TemplateLine line in messageActivity.Text)
    {  
            this.Write("\n                \"\"\"");

        foreach (string text in line.ToTemplateString().ByLine())
        { 
            this.Write("\n                ");
            this.Write(this.ToStringHelper.ToStringWithCulture(text));

        } 
            this.Write("\n                \"\"\"");

    } 
     
            this.Write("\n            );\n        AgentResponse response = new([new ChatMessage(ChatRole.As" +
                    "sistant, activityText)]);\n        await context.AddEventAsync(new AgentResponseE" +
                    "vent(this.Id, response)).ConfigureAwait(false);");

} 
            this.Write("\n\n        return default;\n    }\n}");
            return this.GenerationEnvironment.ToString();
        }

void EvaluateMessageTemplate(TemplateLine templateLine, string variableName)
{
    if (templateLine is not null)
    {
this.Write("\n        string ");

this.Write(this.ToStringHelper.ToStringWithCulture(variableName));

this.Write(" =\n            await context.FormatTemplateAsync(\n                \"\"\"");


                FormatMessageTemplate(templateLine); 
this.Write("\n                \"\"\");");


    }
    else
    {
this.Write("\n        string? ");

this.Write(this.ToStringHelper.ToStringWithCulture(variableName));

this.Write(" = null;");


    }
}

void FormatMessageTemplate(TemplateLine line)
{
    foreach (string text in line.ToTemplateString().ByLine())
    { 
this.Write("\n                ");

this.Write(this.ToStringHelper.ToStringWithCulture(text));


    }
}

    }
}
