// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Microsoft.Agents.AI.Workflows.Declarative.CodeGen
{
    using Microsoft.Agents.ObjectModel;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    internal partial class SetVariableTemplate : ActionTemplate
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n/// <summary>\n/// Assigns an evaluated expression, other variable, or literal va" +
                    "lue to the  \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Model.Variable));
            this.Write("\" variable.\n/// </summary>\ninternal sealed class ");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Name));
            this.Write("Executor(FormulaSession session) : ActionExecutor(id: \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Id));
            this.Write("\", session)\n{\n    // <inheritdoc />\n    protected override async ValueTask<object" +
                    "?> ExecuteAsync(IWorkflowContext context, CancellationToken cancellationToken)\n " +
                    "   {");
 
        EvaluateValueExpression(this.Model.Value, "evaluatedValue");
        AssignVariable(this.Variable, "evaluatedValue"); 
            this.Write("\n        return default;\n    }\n}\n");
            return this.GenerationEnvironment.ToString();
        }

void AssignVariable(PropertyPath targetVariable, string valueVariable, bool tightFormat = false)
{
    if (targetVariable is not null)
    {
this.Write("\n        await context.QueueStateUpdateAsync(key: \"");

this.Write(this.ToStringHelper.ToStringWithCulture(VariableName(targetVariable)));

this.Write("\", value: ");

this.Write(this.ToStringHelper.ToStringWithCulture(valueVariable));

this.Write(", scopeName: \"");

this.Write(this.ToStringHelper.ToStringWithCulture(VariableScope(targetVariable)));

this.Write("\").ConfigureAwait(false);");


        if (!tightFormat)
        {
this.Write("\n        ");

}
    }
}


void EvaluateValueExpression(ValueExpression expression, string targetVariable) =>
    EvaluateValueExpression<object>(expression, targetVariable);

void EvaluateValueExpression<TValue>(ValueExpression expression, string targetVariable)
{
    if (expression is null)
    {
this.Write("\n        ");

this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeAlias<TValue>()));

this.Write("? ");

this.Write(this.ToStringHelper.ToStringWithCulture(targetVariable));

this.Write(" = null;");

 
    }
    else if (expression.IsLiteral)
    {
this.Write("\n        ");

this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeAlias<TValue>()));

this.Write("? ");

this.Write(this.ToStringHelper.ToStringWithCulture(targetVariable));

this.Write(" = ");

this.Write(this.ToStringHelper.ToStringWithCulture(FormatDataValue(expression.LiteralValue)));

this.Write(";");

 
    }
    else if (expression.IsVariableReference && expression.VariableReference.SegmentCount == 2)
    {
this.Write("\n        ");

this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeAlias<TValue>()));

this.Write("? ");

this.Write(this.ToStringHelper.ToStringWithCulture(targetVariable));

this.Write(" = await context.ReadStateAsync<");

this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeAlias<TValue>()));

this.Write(">(key: \"");

this.Write(this.ToStringHelper.ToStringWithCulture(expression.VariableReference.VariableName));

this.Write("\", scopeName: \"");

this.Write(this.ToStringHelper.ToStringWithCulture(expression.VariableReference.NamespaceAlias));

this.Write("\").ConfigureAwait(false);");


    }
    else if (expression.IsVariableReference)
    {
this.Write("\n        ");

this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeAlias<TValue>()));

this.Write("? ");

this.Write(this.ToStringHelper.ToStringWithCulture(targetVariable));

this.Write(" = await context.EvaluateValueAsync<");

this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeAlias<TValue>()));

this.Write(">(");

this.Write(this.ToStringHelper.ToStringWithCulture(FormatStringValue(expression.VariableReference.ToString())));

this.Write(").ConfigureAwait(false);");

 
    }
    else
    {
this.Write("\n        ");

this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeAlias<TValue>()));

this.Write("? ");

this.Write(this.ToStringHelper.ToStringWithCulture(targetVariable));

this.Write(" = await context.EvaluateValueAsync<");

this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeAlias<TValue>()));

this.Write(">(");

this.Write(this.ToStringHelper.ToStringWithCulture(FormatStringValue(expression.ExpressionText)));

this.Write(").ConfigureAwait(false);");

 
    }
}

    }
}
