name: Issue Report
description: Report a bug, request a feature, or ask a question about Microsoft Agent Framework
title: "[Issue]: "
labels: ["triage"]
body:
  - type: dropdown
    id: language
    attributes:
      label: Language
      description: Which language/SDK are you using?
      options:
        - .NET
        - Python
        - None / Not Applicable
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Type of Issue
      description: What type of issue is this?
      options:
        - Bug
        - Feature Request
        - Question
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Version Information
        Please provide the version of the package(s) you are using. Select the relevant packages below.

  - type: markdown
    attributes:
      value: "### .NET Packages"

  - type: input
    id: dotnet-agents-ai
    attributes:
      label: Microsoft.Agents.AI
      description: Version of Microsoft.Agents.AI (e.g., 1.0.0)
      placeholder: "e.g., 1.0.0"
    validations:
      required: false

  - type: input
    id: dotnet-agents-ai-abstractions
    attributes:
      label: Microsoft.Agents.AI.Abstractions
      description: Version of Microsoft.Agents.AI.Abstractions
      placeholder: "e.g., 1.0.0"
    validations:
      required: false

  - type: input
    id: dotnet-agents-ai-openai
    attributes:
      label: Microsoft.Agents.AI.OpenAI
      description: Version of Microsoft.Agents.AI.OpenAI
      placeholder: "e.g., 1.0.0"
    validations:
      required: false

  - type: input
    id: dotnet-agents-ai-azureai
    attributes:
      label: Microsoft.Agents.AI.AzureAI
      description: Version of Microsoft.Agents.AI.AzureAI
      placeholder: "e.g., 1.0.0"
    validations:
      required: false

  - type: input
    id: dotnet-agents-ai-anthropic
    attributes:
      label: Microsoft.Agents.AI.Anthropic
      description: Version of Microsoft.Agents.AI.Anthropic
      placeholder: "e.g., 1.0.0"
    validations:
      required: false

  - type: input
    id: dotnet-agents-ai-hosting
    attributes:
      label: Microsoft.Agents.AI.Hosting
      description: Version of Microsoft.Agents.AI.Hosting
      placeholder: "e.g., 1.0.0"
    validations:
      required: false

  - type: input
    id: dotnet-agents-ai-workflows
    attributes:
      label: Microsoft.Agents.AI.Workflows
      description: Version of Microsoft.Agents.AI.Workflows
      placeholder: "e.g., 1.0.0"
    validations:
      required: false

  - type: input
    id: dotnet-other-packages
    attributes:
      label: Other .NET Packages
      description: List any other Microsoft.Agents.* packages and versions you are using
      placeholder: "e.g., Microsoft.Agents.AI.CopilotStudio: 1.0.0, Microsoft.Agents.AI.Purview: 1.0.0"
    validations:
      required: false

  - type: markdown
    attributes:
      value: "### Python Packages"

  - type: input
    id: python-core
    attributes:
      label: agent-framework-core
      description: Version of agent-framework-core
      placeholder: "e.g., 1.0.0b1"
    validations:
      required: false

  - type: input
    id: python-azure-ai
    attributes:
      label: agent-framework-azure-ai
      description: Version of agent-framework-azure-ai
      placeholder: "e.g., 1.0.0b1"
    validations:
      required: false

  - type: input
    id: python-anthropic
    attributes:
      label: agent-framework-anthropic
      description: Version of agent-framework-anthropic
      placeholder: "e.g., 1.0.0b1"
    validations:
      required: false

  - type: input
    id: python-azurefunctions
    attributes:
      label: agent-framework-azurefunctions
      description: Version of agent-framework-azurefunctions
      placeholder: "e.g., 1.0.0b1"
    validations:
      required: false

  - type: input
    id: python-other-packages
    attributes:
      label: Other Python Packages
      description: List any other agent-framework-* packages and versions you are using
      placeholder: "e.g., agent-framework-mem0: 1.0.0b1, agent-framework-redis: 1.0.0b1"
    validations:
      required: false

  - type: markdown
    attributes:
      value: "---"

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and detailed description of the issue, feature request, or question.
      placeholder: |
        For bugs: Describe what happened, what you expected to happen, and steps to reproduce.
        For features: Describe the feature you'd like and why it would be useful.
        For questions: Describe what you're trying to accomplish.
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: If applicable, provide a minimal code sample that demonstrates the issue or your use case.
      placeholder: |
        ```python
        # Your code here
        ```

        or

        ```csharp
        // Your code here
        ```
      render: markdown
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, error messages, or stack traces that might be helpful.
      placeholder: "Any additional information..."
    validations:
      required: false
