// Copyright (c) Microsoft. All rights reserved.

using System;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using Azure.AI.Projects.Memory;
using OpenAI.Responses;

namespace Microsoft.Agents.AI.Foundry.UnitTests.Memory;

/// <summary>Verifies that the mock transport handles requests generated by the memory SDK.</summary>
public sealed class TestableAIProjectClientTests
{
    /// <summary>Verifies the update action route and its accepted response.</summary>
    [Fact]
    public async Task UpdateMemoriesAsync_MatchesSdkRequestAsync()
    {
        // Arrange
        using TestableAIProjectClient testClient = new();
        MemoryUpdateOptions options = new("test-scope");
        options.Items.Add(ResponseItem.CreateUserMessageItem("I prefer concise answers."));

        // Act
        var result = await testClient.Client.MemoryStores.UpdateMemoriesAsync("test-store", options);

        // Assert
        Assert.Equal("test-update-id", result.Value.UpdateId);
        Assert.Equal((int)HttpStatusCode.Accepted, result.GetRawResponse().Status);
        Assert.Equal(HttpMethod.Post, testClient.Handler.LastRequestMethod);
        Assert.Equal("/api/projects/test-project/memory_stores/test-store:update_memories", new Uri(testClient.Handler.LastRequestUri!).AbsolutePath);
    }

    /// <summary>Verifies that deleting a scope uses POST and returns its result.</summary>
    [Fact]
    public async Task DeleteScopeAsync_MatchesSdkRequestAsync()
    {
        // Arrange
        using TestableAIProjectClient testClient = new();

        // Act
        var result = await testClient.Client.MemoryStores.DeleteScopeAsync("test-store", "test-scope");

        // Assert
        Assert.True(result.Value.IsDeleted);
        Assert.Equal("test-scope", result.Value.Scope);
        Assert.Equal((int)HttpStatusCode.OK, result.GetRawResponse().Status);
        Assert.Equal(HttpMethod.Post, testClient.Handler.LastRequestMethod);
        Assert.Equal("/api/projects/test-project/memory_stores/test-store:delete_scope", new Uri(testClient.Handler.LastRequestUri!).AbsolutePath);
    }

    /// <summary>Verifies the collection route used to create a memory store.</summary>
    [Fact]
    public async Task CreateMemoryStoreAsync_MatchesSdkRequestAsync()
    {
        // Arrange
        using TestableAIProjectClient testClient = new();
        MemoryStoreDefaultDefinition definition = new("chat-model", "embedding-model");

        // Act
        var result = await testClient.Client.MemoryStores.CreateMemoryStoreAsync("test-store", definition);

        // Assert
        Assert.Equal("test-store", result.Value.Name);
        Assert.Equal((int)HttpStatusCode.OK, result.GetRawResponse().Status);
        Assert.Equal(HttpMethod.Post, testClient.Handler.LastRequestMethod);
        Assert.Equal("/api/projects/test-project/memory_stores", new Uri(testClient.Handler.LastRequestUri!).AbsolutePath);
    }

    /// <summary>Verifies that retrieving a memory store uses the configured mock result.</summary>
    [Fact]
    public async Task GetMemoryStoreAsync_MatchesSdkRequestAsync()
    {
        // Arrange
        using TestableAIProjectClient testClient = new(getStoreStatusCode: HttpStatusCode.OK);

        // Act
        var result = await testClient.Client.MemoryStores.GetMemoryStoreAsync("test-store");

        // Assert
        Assert.Equal("test-store", result.Value.Name);
        Assert.Equal((int)HttpStatusCode.OK, result.GetRawResponse().Status);
        Assert.Equal(HttpMethod.Get, testClient.Handler.LastRequestMethod);
        Assert.Equal("/api/projects/test-project/memory_stores/test-store", new Uri(testClient.Handler.LastRequestUri!).AbsolutePath);
    }
}
