# Copyright (c) Microsoft. All rights reserved.

# Type stubs for the agent_framework.foundry lazy-loading namespace.
# Install the relevant packages for full type support.

from agent_framework_anthropic import AnthropicFoundryClient, RawAnthropicFoundryClient
from agent_framework_azure_contentunderstanding import (
    AnalysisSection,
    ContentUnderstandingContextProvider,
    DocumentStatus,
    FileSearchBackend,
    FileSearchConfig,
)
from agent_framework_foundry import (
    FOUNDRY_HOSTED_AGENT_SESSION_ID_KEY,
    FoundryAgent,
    FoundryChatClient,
    FoundryChatOptions,
    FoundryEmbeddingClient,
    FoundryEmbeddingOptions,
    FoundryEmbeddingSettings,
    FoundryEvals,
    FoundryMemoryProvider,
    GeneratedEvaluatorRef,
    RawFoundryAgent,
    RawFoundryAgentChatClient,
    RawFoundryChatClient,
    RawFoundryEmbeddingClient,
    evaluate_foundry_target,
    evaluate_traces,
    to_prompt_agent,
)
from agent_framework_foundry_hosting import (
    AgentSessionStoreProvider,
    CheckpointStoreProvider,
    ContextScopedStoreProvider,
    FoundryAgentSessionStore,
    FoundryCheckpointStore,
    FoundryFunctionApprovalStore,
    FoundryToolbox,
    FunctionApprovalStore,
    FunctionApprovalStoreProvider,
    InvocationsHostServer,
    ResponsesHostServer,
    StoreProvider,
)
from agent_framework_foundry_local import (
    FoundryLocalChatOptions,
    FoundryLocalClient,
    FoundryLocalSettings,
)

__all__ = [
    "FOUNDRY_HOSTED_AGENT_SESSION_ID_KEY",
    "AgentSessionStoreProvider",
    "AnalysisSection",
    "AnthropicFoundryClient",
    "CheckpointStoreProvider",
    "ContentUnderstandingContextProvider",
    "ContextScopedStoreProvider",
    "DocumentStatus",
    "FileSearchBackend",
    "FileSearchConfig",
    "FoundryAgent",
    "FoundryAgentSessionStore",
    "FoundryChatClient",
    "FoundryChatOptions",
    "FoundryCheckpointStore",
    "FoundryEmbeddingClient",
    "FoundryEmbeddingOptions",
    "FoundryEmbeddingSettings",
    "FoundryEvals",
    "FoundryFunctionApprovalStore",
    "FoundryLocalChatOptions",
    "FoundryLocalClient",
    "FoundryLocalSettings",
    "FoundryMemoryProvider",
    "FoundryToolbox",
    "FunctionApprovalStore",
    "FunctionApprovalStoreProvider",
    "GeneratedEvaluatorRef",
    "InvocationsHostServer",
    "RawAnthropicFoundryClient",
    "RawFoundryAgent",
    "RawFoundryAgentChatClient",
    "RawFoundryChatClient",
    "RawFoundryEmbeddingClient",
    "ResponsesHostServer",
    "StoreProvider",
    "evaluate_foundry_target",
    "evaluate_traces",
    "to_prompt_agent",
]
