// Copyright (c) Microsoft. All rights reserved.

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.AI;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;

namespace Microsoft.Agents.AI;

/// <summary>
/// A delegating chat client that strengthens the human-in-the-loop tool-approval control by binding each inbound
/// <see cref="ToolApprovalResponseContent"/> to the model-originated <see cref="ToolApprovalRequestContent"/> that
/// the framework actually surfaced, so an approved tool call always matches what a human was asked to approve.
/// </summary>
/// <remarks>
/// <para>
/// <see cref="FunctionInvokingChatClient"/> (FICC) executes the <see cref="ToolApprovalResponseContent.ToolCall"/>
/// carried by an approval response. This decorator adds an extra layer of assurance above FICC: it guarantees that
/// only approvals the framework actually requested are honored, and that an approved call runs with exactly the tool
/// name and arguments that were surfaced for approval.
/// This binding also applies to tools that do not require human approval.
/// </para>
/// <para>
/// This decorator sits above <see cref="FunctionInvokingChatClient"/> in the pipeline. On outbound responses it
/// records every model-originated <see cref="ToolApprovalRequestContent"/> that FICC surfaced into the session's
/// <see cref="AgentSessionStateBag"/>, keyed by request id. On inbound requests it processes each
/// <see cref="ToolApprovalResponseContent"/> before it reaches FICC:
/// <list type="bullet">
/// <item>If a recorded pending request exists for the response's request id, the response's tool call is rebound to
/// the recorded (model-originated) tool call, so the approved call always matches the surfaced request's tool name
/// and arguments. The pending entry is then consumed so an approval is honored only once.</item>
/// <item>If no recorded pending request exists, the response is ignored, so only approvals tied to a genuine,
/// framework-issued request take effect.</item>
/// <item>Any recorded request left unanswered on the next run is automatically rejected, allowing the
/// conversation to continue without executing the unapproved tool.</item>
/// </list>
/// </para>
/// <para>
/// Approval responses are grouped before new caller messages so the tool results generated by
/// <see cref="FunctionInvokingChatClient"/> precede later questions. The <see cref="FunctionCallContent"/>
/// objects inside approval requests and responses are copied before being passed to that client, which
/// changes their <see cref="FunctionCallContent.InformationalOnly"/> flags while processing approvals.
/// </para>
/// <para>
/// Generated rejection responses are returned to the caller before the tool-result messages, allowing
/// end-of-run history saving to record the decision as well as its result. Caller-supplied responses are not
/// returned again. In streaming runs, a generated rejection can be emitted before a later service call fails;
/// receiving that decision does not mean the run succeeded.
/// </para>
/// <para>
/// The authority for an approval is always the state the framework itself recorded when it surfaced the request.
/// An approval request that merely appears in the caller-supplied message history is never, by itself, proof
/// that the framework asked a human to approve it; without this rule a caller could supply a fabricated request
/// together with its own approval and authorize an arbitrary tool call. A host that cannot record approval
/// requests server-side therefore cannot resume an approval, and should disable approval-response binding
/// altogether rather than rely on the history it replays.
/// </para>
/// <para>
/// This decorator operates within the context of a running <see cref="AIAgent"/> with an active
/// <see cref="AgentRunContext.Session"/>. When invoked without an ambient run context or session (for example when
/// the chat client is used directly outside of an agent run), the decorator becomes a no-op: it passes the request
/// through unchanged and logs a warning, because there is no framework-tracked pending state to validate against.
/// </para>
/// </remarks>
internal sealed partial class ApprovalResponseBindingChatClient : DelegatingChatClient
{
    /// <summary>
    /// The key used in <see cref="AgentSessionStateBag"/> to store the model-originated pending approval requests
    /// between agent runs.
    /// </summary>
    internal const string StateBagKey = "_pendingApprovalRequests";

    private readonly ILogger _logger;

    private bool _warnedNoSession;

    /// <summary>
    /// Initializes a new instance of the <see cref="ApprovalResponseBindingChatClient"/> class.
    /// </summary>
    /// <param name="innerClient">The underlying chat client (typically the pipeline containing <see cref="FunctionInvokingChatClient"/>).</param>
    /// <param name="loggerFactory">An optional <see cref="ILoggerFactory"/> used to create a logger for diagnostics.</param>
    public ApprovalResponseBindingChatClient(IChatClient innerClient, ILoggerFactory? loggerFactory = null)
        : base(innerClient)
        => this._logger = (loggerFactory ?? NullLoggerFactory.Instance).CreateLogger<ApprovalResponseBindingChatClient>();

    /// <inheritdoc/>
    public override async Task<ChatResponse> GetResponseAsync(
        IEnumerable<ChatMessage> messages,
        ChatOptions? options = null,
        CancellationToken cancellationToken = default)
    {
        if (!this.TryGetSession(out var session))
        {
            return await base.GetResponseAsync(messages, options, cancellationToken).ConfigureAwait(false);
        }

        var (messagesToSend, hasPendingRequests, generatedRejections) = this.ValidateInboundApprovalResponses(messages, session);

        var response = await base.GetResponseAsync(messagesToSend, options, cancellationToken).ConfigureAwait(false);

        if (generatedRejections is not null)
        {
            response.Messages = [generatedRejections, .. response.Messages];
        }

        // The records are consumed only now that the run has succeeded, so a failed run leaves them intact and the
        // caller can supply the same approval response again. This runs before the requests surfaced by this run
        // are recorded, so it never discards those.
        if (hasPendingRequests)
        {
            session.StateBag.TryRemoveValue(StateBagKey);
        }

        this.RecordPendingApprovalRequests(response.Messages, session);

        return response;
    }

    /// <inheritdoc/>
    public override async IAsyncEnumerable<ChatResponseUpdate> GetStreamingResponseAsync(
        IEnumerable<ChatMessage> messages,
        ChatOptions? options = null,
        [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        if (!this.TryGetSession(out var session))
        {
            await foreach (var passthrough in base.GetStreamingResponseAsync(messages, options, cancellationToken).ConfigureAwait(false))
            {
                yield return passthrough;
            }

            yield break;
        }

        var (messagesToSend, hasPendingRequests, generatedRejections) = this.ValidateInboundApprovalResponses(messages, session);

        List<ToolApprovalRequestContent>? emitted = null;

        // Set only once the stream has run to completion, so that any abnormal end - an exception from the inner
        // client, a cancellation, or a consumer that stops enumerating early - leaves the records intact and lets the
        // caller supply the same approval response again. A caught exception is not enough on its own: breaking out of
        // the enumeration disposes this iterator without throwing, and the run then persists nothing either.
        bool completedNormally = false;

        try
        {
            if (generatedRejections is not null)
            {
                yield return new ChatResponseUpdate(generatedRejections.Role, generatedRejections.Contents)
                {
                    MessageId = generatedRejections.MessageId,
                };
            }

            await foreach (var update in base.GetStreamingResponseAsync(messagesToSend, options, cancellationToken).ConfigureAwait(false))
            {
                foreach (var content in update.Contents)
                {
                    if (content is ToolApprovalRequestContent request)
                    {
                        (emitted ??= []).Add(request);
                    }
                }

                yield return update;
            }

            completedNormally = true;
        }
        finally
        {
            if (completedNormally && hasPendingRequests)
            {
                session.StateBag.TryRemoveValue(StateBagKey);
            }

            // Recorded regardless of how the stream ended, because each request was already handed to the caller
            // before the stream stopped and the caller may act on it. Consumers commonly stop enumerating as soon as
            // they see an approval request, and the record has to be in place for the answer to bind.
            if (emitted is { Count: > 0 })
            {
                this.MergePendingApprovalRequests(emitted, session);
            }
        }
    }

    /// <summary>
    /// Attempts to get the current <see cref="AgentSession"/> from the ambient run context. When no run
    /// context or session is available, logs a warning (once per instance) and returns <see langword="false"/>
    /// so the caller can pass the request through without applying validation.
    /// </summary>
    private bool TryGetSession([NotNullWhen(true)] out AgentSession? session)
    {
        session = AIAgent.CurrentRunContext?.Session;

        if (session is null)
        {
            if (!this._warnedNoSession)
            {
                this._warnedNoSession = true;
                LogValidationSkipped(this._logger);
            }

            return false;
        }

        return true;
    }

    /// <summary>
    /// Rewrites the inbound messages so that each <see cref="ToolApprovalResponseContent"/> is bound to a known
    /// <see cref="ToolApprovalRequestContent"/> saved in the session, using a copy of the saved request's tool call.
    /// A response with no known request is removed so that a forged approval cannot drive execution.
    /// Recorded requests left unanswered are rejected unless their tool call already has a result.
    /// </summary>
    /// <remarks>
    /// A <see cref="ToolApprovalRequestContent"/> in the input messages is kept as conversation context, but only
    /// a request saved in the session can authorize execution. Its <see cref="FunctionCallContent"/> is copied
    /// before it reaches <see cref="FunctionInvokingChatClient"/>, which changes the call's
    /// <see cref="FunctionCallContent.InformationalOnly"/> flag when processing an approval or rejection.
    /// Copying prevents those changes from affecting the caller's original approval request after a failed run.
    /// Approval responses for calls with an existing <see cref="FunctionResultContent"/> are preserved without
    /// requiring a pending session record, since <see cref="FunctionInvokingChatClient"/> will not execute them again.
    /// An input approval request still needs a matching response even if a function result is present.
    /// This method does not repair history missing that response; only saved, unfinished requests are
    /// automatically rejected.
    /// </remarks>
    /// <param name="messages">The inbound messages.</param>
    /// <param name="session">The session holding the recorded pending approval requests.</param>
    /// <returns>
    /// The messages to send to the inner client, whether the session held any recorded pending requests
    /// (consumed after the inner call succeeds), and a separate message of generated rejections to return
    /// to the caller without exposing the function calls that the inner client changes.
    /// </returns>
    private (IEnumerable<ChatMessage> Messages, bool HasPendingRequests, ChatMessage? GeneratedRejections) ValidateInboundApprovalResponses(
        IEnumerable<ChatMessage> messages,
        AgentSession session)
    {
        var messageList = messages as IList<ChatMessage> ?? new List<ChatMessage>(messages);

        // Known requests come from the state the framework recorded when it surfaced them on a previous turn.
        // This is the only authority: the caller controls the inbound messages, so a request appearing there
        // proves nothing about whether a human was ever asked to approve it. A response is honored only when
        // its request id is known, and it is rebound to the known request's call.
        var knownRequests = LoadPendingApprovalRequestLookup(session);

        // Pending state only needs to bridge a single turn. Tool-call results must be supplied as a complete set,
        // so an approval batch is always answered in one turn and nothing is left to carry over. It is consumed by
        // the caller once the inner call has succeeded rather than here, because a run that fails persists neither
        // the approval response nor anything else, and the caller must be able to supply the same response again.
        var hasPendingRequests = knownRequests.Count > 0;

        // Tool calls that already carry a result in the inbound messages. The approval gate guards execution, and
        // a call whose result is already present will not be executed again, so its approval is settled history
        // rather than a pending authorization. Validating it would serve no purpose and would reject every host
        // that replays a completed conversation.
        //
        // This relies on an invariant that FunctionInvokingChatClient enforces itself: it gathers the call ids of
        // every FunctionResultContent in the messages and skips any approval response whose call id is in that
        // set, so such a response can never reach invocation. A caller that fabricates a result in order to reach
        // the exemption below therefore also guarantees the call will not run.
        HashSet<string>? settledCallIds = null;

        bool hasResponse = false;
        bool hasRequest = false;
        foreach (var message in messageList)
        {
            foreach (var content in message.Contents)
            {
                if (content is FunctionResultContent functionResult)
                {
                    (settledCallIds ??= new HashSet<string>(StringComparer.Ordinal)).Add(functionResult.CallId);
                }
                else if (content is ToolApprovalResponseContent)
                {
                    hasResponse = true;
                }
                else if (content is ToolApprovalRequestContent { ToolCall: FunctionCallContent { InformationalOnly: false } })
                {
                    hasRequest = true;
                }
            }
        }

        if (!hasResponse && !hasPendingRequests && !hasRequest)
        {
            return (messageList, hasPendingRequests, null);
        }

        // Copy-on-write: only allocate a new message list once a message is actually modified.
        List<ChatMessage>? result = null;

        // Bind incoming approval responses to the known approval requests.
        for (int i = 0; i < messageList.Count; i++)
        {
            var message = messageList[i];
            var mutableContentsBuffer = this.BindApprovalContents(message, knownRequests, settledCallIds);

            if (mutableContentsBuffer is null)
            {
                // Message unchanged: keep the original (backfilling only if an earlier message was rewritten).
                result?.Add(message);
                continue;
            }

            // First rewritten message: backfill the result with the unchanged prefix.
            if (result is null)
            {
                result = new List<ChatMessage>(messageList.Count);
                for (int k = 0; k < i; k++)
                {
                    result.Add(messageList[k]);
                }
            }

            // Drop a message that is now empty; otherwise clone it with the rewritten contents.
            if (mutableContentsBuffer.Count > 0)
            {
                var cloned = message.Clone();
                cloned.Contents = mutableContentsBuffer;
                result.Add(cloned);
            }
        }

        // Create a rejection response for any known requests that weren't answered,
        // to avoid failing the request and allow easier recovery when clients have
        // lost the list of requests that they need to answer, but need to continue
        // the conversation.
        List<AIContent>? rejections = null;
        ChatMessage? generatedRejections = null;
        foreach (var request in knownRequests.Values)
        {
            if (settledCallIds?.Contains(request.ToolCall.CallId) is true)
            {
                continue;
            }

            // FICC changes the rejection's FunctionCallContent.InformationalOnly flag.
            // Copy the saved request's call so a failed rejection attempt leaves it usable for retry.
            var rejection = ToolApprovalHelpers.SnapshotRequest(request).CreateResponse(
                approved: false,
                reason: "No approval response was provided for this approval required tool call.");
            (rejections ??= []).Add(rejection);
            generatedRejections ??= new ChatMessage(ChatRole.User, [])
            {
                MessageId = Guid.NewGuid().ToString("N"),
            };
            // Keep the returned decision separate from the call FICC marks InformationalOnly.
            generatedRejections.Contents.Add(CopyResponse(rejection, ToolApprovalHelpers.SnapshotRequest(request).ToolCall));
        }

        return (ToolApprovalHelpers.PrepareApprovalMessages(result ?? messageList, rejections), hasPendingRequests, generatedRejections);
    }

    /// <summary>
    /// Copies the function calls in the message's <see cref="ToolApprovalRequestContent"/> items whose
    /// <see cref="FunctionCallContent.InformationalOnly"/> flag is <see langword="false"/>.
    /// Binds each <see cref="ToolApprovalResponseContent"/> to a copy of the tool call saved under its request id
    /// in <paramref name="knownRequests"/>.
    /// Returns <see langword="null"/> when the message needs no change, or the rewritten content list (which may be
    /// empty, indicating the message should be dropped) when a change is required. Responses referring to
    /// call ids in <paramref name="settledCallIds"/> are preserved unchanged because their existing results
    /// prevent <see cref="FunctionInvokingChatClient"/> from executing those calls again.
    /// </summary>
    private List<AIContent>? BindApprovalContents(
        ChatMessage message,
        Dictionary<string, ToolApprovalRequestContent> knownRequests,
        HashSet<string>? settledCallIds)
    {
        var contents = message.Contents;
        List<AIContent>? mutableContentsBuffer = null;

        for (int j = 0; j < contents.Count; j++)
        {
            var content = contents[j];

            if (content is ToolApprovalRequestContent { ToolCall: FunctionCallContent { InformationalOnly: false } } request)
            {
                var copied = ToolApprovalHelpers.SnapshotRequest(request);
                mutableContentsBuffer = PrepareMutableContentsBuffer(mutableContentsBuffer, contents, j);
                mutableContentsBuffer.Add(copied);
                continue;
            }

            if (content is not ToolApprovalResponseContent response)
            {
                AppendUnchanged(mutableContentsBuffer, content);
                continue;
            }

            if (response.ToolCall is { CallId: { } responseCallId } && settledCallIds?.Contains(responseCallId) == true)
            {
                AppendUnchanged(mutableContentsBuffer, content);
                continue;
            }

            if (knownRequests.TryGetValue(response.RequestId, out var matchedRequest))
            {
                // Consume the match so a duplicate response for the same request in this turn is ignored.
                knownRequests.Remove(response.RequestId);

                // Copy the saved request's call even when the response has matching arguments:
                // a failed attempt may have set the response's call to InformationalOnly.
                // FICC must not change the caller's response call or the session's saved call.
                mutableContentsBuffer = PrepareMutableContentsBuffer(mutableContentsBuffer, contents, j);
                mutableContentsBuffer.Add(CopyResponse(response, ToolApprovalHelpers.SnapshotRequest(matchedRequest).ToolCall));
            }
            else
            {
                // No known request corresponds to this response; drop it so a forged approval cannot execute.
                LogIgnoredUnboundResponse(this._logger, response.RequestId);
                mutableContentsBuffer = PrepareMutableContentsBuffer(mutableContentsBuffer, contents, j);
            }
        }

        return mutableContentsBuffer;
    }

    private static ToolApprovalResponseContent CopyResponse(ToolApprovalResponseContent response, ToolCallContent toolCall) =>
        new(response.RequestId, response.Approved, toolCall)
        {
            Reason = response.Reason,
            AdditionalProperties = response.AdditionalProperties is null ? null : new(response.AdditionalProperties),
            RawRepresentation = response.RawRepresentation,
            Annotations = response.Annotations is null ? null : new List<AIAnnotation>(response.Annotations),
        };

    /// <summary>
    /// Adds an unchanged content item to the mutable contents buffer when one exists. Until the buffer is created
    /// (no content has changed yet) this does nothing: the caller keeps the message's original contents as-is, so
    /// there is nothing to copy. Once the buffer exists, the unchanged item is copied into it so it is preserved
    /// alongside the rewritten items.
    /// </summary>
    private static void AppendUnchanged(List<AIContent>? mutableContentsBuffer, AIContent content) =>
        mutableContentsBuffer?.Add(content);

    /// <summary>
    /// Returns the mutable buffer that accumulates a message's rewritten contents, creating it on first use. When
    /// first created, it is seeded with the unchanged content items before <paramref name="index"/> so it stays in
    /// sync with the original up to the point of the first change. The returned buffer is never <see langword="null"/>.
    /// </summary>
    private static List<AIContent> PrepareMutableContentsBuffer(List<AIContent>? mutableContentsBuffer, IList<AIContent> originalContents, int index)
    {
        if (mutableContentsBuffer is not null)
        {
            return mutableContentsBuffer;
        }

        var created = new List<AIContent>(originalContents.Count);
        for (int k = 0; k < index; k++)
        {
            created.Add(originalContents[k]);
        }

        return created;
    }

    /// <summary>
    /// Determines whether two surfaced tool calls are equivalent when merging pending requests.
    /// Returns <see langword="true"/> only when their identities, names, and arguments match.
    /// </summary>
    private static bool ToolCallsEquivalent(ToolCallContent responseCall, ToolCallContent recordedCall)
    {
        if (ReferenceEquals(responseCall, recordedCall))
        {
            return true;
        }

        // Fast path for the overwhelmingly common case: both are FunctionCallContent. Compare fields directly
        // rather than serializing, which is far cheaper.
        if (responseCall is FunctionCallContent responseFunction && recordedCall is FunctionCallContent recordedFunction)
        {
            return string.Equals(responseFunction.CallId, recordedFunction.CallId, StringComparison.Ordinal)
                && string.Equals(responseFunction.Name, recordedFunction.Name, StringComparison.Ordinal)
                && ArgumentsEquivalent(responseFunction.Arguments, recordedFunction.Arguments);
        }

        // Unknown call shapes cannot safely be treated as the same pending request.
        return false;
    }

    /// <summary>
    /// Determines whether two function-call argument dictionaries are equivalent. Uses a shallow value
    /// comparison; when values cannot be proven equal (for example after a serialization round-trip changes the
    /// runtime type), this returns <see langword="false"/> to avoid merging distinct pending requests.
    /// </summary>
    private static bool ArgumentsEquivalent(IDictionary<string, object?>? responseArguments, IDictionary<string, object?>? recordedArguments)
    {
        if (ReferenceEquals(responseArguments, recordedArguments))
        {
            return true;
        }

        if (responseArguments is null || recordedArguments is null || responseArguments.Count != recordedArguments.Count)
        {
            return false;
        }

        foreach (var pair in responseArguments)
        {
            if (!recordedArguments.TryGetValue(pair.Key, out var recordedValue) || !Equals(pair.Value, recordedValue))
            {
                return false;
            }
        }

        return true;
    }

    private static Dictionary<string, ToolApprovalRequestContent> LoadPendingApprovalRequestLookup(AgentSession session)
    {
        var pendingRequests = LoadPendingApprovalRequests(session);
        var byRequestId = new Dictionary<string, ToolApprovalRequestContent>(pendingRequests.Count, StringComparer.Ordinal);
        foreach (var request in pendingRequests)
        {
            byRequestId[request.RequestId] = request;
        }

        return byRequestId;
    }

    /// <summary>
    /// Records model-originated <see cref="ToolApprovalRequestContent"/> items found in the response messages into
    /// the session so they can be matched against the caller's approval responses on the next request.
    /// </summary>
    private void RecordPendingApprovalRequests(IList<ChatMessage> messages, AgentSession session)
    {
        List<ToolApprovalRequestContent>? emitted = null;

        foreach (var message in messages)
        {
            foreach (var content in message.Contents)
            {
                if (content is ToolApprovalRequestContent request)
                {
                    (emitted ??= []).Add(request);
                }
            }
        }

        if (emitted is { Count: > 0 })
        {
            this.MergePendingApprovalRequests(emitted, session);
        }
    }

    /// <summary>
    /// Merges newly surfaced approval requests into the recorded pending set, de-duplicating by request id.
    /// </summary>
    /// <remarks>
    /// A request id is not guaranteed to be unique: <see cref="FunctionInvokingChatClient"/> composes it as
    /// <c>"ficc_{CallId}"</c>, so a provider that reuses a call id produces a collision. Re-surfacing the same
    /// call under a known id is harmless and ignored, but if a <em>different</em> call appears under an id that
    /// is already pending there is no way to tell which call a human's answer refers to. That case fails closed:
    /// the id is poisoned and no approval is honored for it, so consent can never be redirected onto a call the
    /// human did not see.
    /// </remarks>
    private void MergePendingApprovalRequests(List<ToolApprovalRequestContent> emitted, AgentSession session)
    {
        var pendingRequests = LoadPendingApprovalRequests(session);

        var known = new Dictionary<string, ToolApprovalRequestContent>(StringComparer.Ordinal);
        foreach (var request in pendingRequests)
        {
            known[request.RequestId] = request;
        }

        HashSet<string>? ambiguousRequestIds = null;
        bool changed = false;

        foreach (var request in emitted)
        {
            if (ambiguousRequestIds?.Contains(request.RequestId) == true)
            {
                continue;
            }

            if (!known.TryGetValue(request.RequestId, out var existing))
            {
                // Store a snapshot so a later mutation of the caller-visible instance cannot change
                // the recorded tool call used to bind the response.
                var snapshot = ToolApprovalHelpers.SnapshotRequest(request);
                known[request.RequestId] = snapshot;
                pendingRequests.Add(snapshot);
                changed = true;
                continue;
            }

            if (ToolCallsEquivalent(request.ToolCall, existing.ToolCall))
            {
                // The same request surfaced again; the recorded snapshot already covers it.
                continue;
            }

            // Collision between two different calls under one request id: neither can be bound safely.
            LogAmbiguousRequestId(this._logger, request.RequestId);
            (ambiguousRequestIds ??= new HashSet<string>(StringComparer.Ordinal)).Add(request.RequestId);
            known.Remove(request.RequestId);
            pendingRequests.RemoveAll(pending => string.Equals(pending.RequestId, request.RequestId, StringComparison.Ordinal));
            changed = true;
        }

        if (changed)
        {
            SavePendingApprovalRequests(pendingRequests, session);
        }
    }

    private static List<ToolApprovalRequestContent> LoadPendingApprovalRequests(AgentSession session)
        => session.StateBag.TryGetValue<List<ToolApprovalRequestContent>>(StateBagKey, out var pendingRequests, AgentJsonUtilities.DefaultOptions)
            && pendingRequests is not null
            ? pendingRequests
            : [];

    private static void SavePendingApprovalRequests(List<ToolApprovalRequestContent> pendingRequests, AgentSession session)
    {
        if (pendingRequests.Count > 0)
        {
            session.StateBag.SetValue(StateBagKey, pendingRequests, AgentJsonUtilities.DefaultOptions);
        }
        else
        {
            session.StateBag.TryRemoveValue(StateBagKey);
        }
    }

    [LoggerMessage(LogLevel.Warning, "ApprovalResponseBindingChatClient was invoked without an active agent run context or session. Approval-response binding is skipped. Invoke the chat client through AIAgent.RunAsync or AIAgent.RunStreamingAsync to enable binding.")]
    private static partial void LogValidationSkipped(ILogger logger);

    [LoggerMessage(LogLevel.Warning, "Ignored a ToolApprovalResponseContent with request id '{RequestId}' that does not correspond to a model-originated approval request surfaced by the framework. Approval requests present only in the caller-supplied chat history are deliberately not trusted for pairing. If this agent legitimately resumes approvals, register an AgentSessionStore so the approval request is recorded server-side when it is surfaced.")]
    private static partial void LogIgnoredUnboundResponse(ILogger logger, string requestId);

    [LoggerMessage(LogLevel.Warning, "Two different tool calls were surfaced for approval under request id '{RequestId}'. The request id is ambiguous, so no approval will be honored for it and the affected tool calls must be requested again.")]
    private static partial void LogAmbiguousRequestId(ILogger logger, string requestId);
}
