// Copyright (c) Microsoft. All rights reserved.

using PredicateT = System.Func<object?, bool>;

namespace Microsoft.Agents.Workflows;

/// <summary>
/// Represents a directed edge between two nodes, optionally associated with a condition that determines whether the
/// edge is active.
/// </summary>
/// <param name="sourceId">The id of the source executor node.</param>
/// <param name="sinkId">The id of the target executor node.</param>
/// <param name="condition">A predicate determining whether the edge is active for a given message.</param>
public sealed class DirectEdgeData(string sourceId, string sinkId, PredicateT? condition = null)
{
    /// <summary>
    /// The Id of the source <see cref="Executor"/> node.
    /// </summary>
    public string SourceId => sourceId;

    /// <summary>
    /// The Id of the destination <see cref="Executor"/> node.
    /// </summary>
    public string SinkId => sinkId;

    /// <summary>
    /// An optional predicate determining whether the edge is active for a given message. If <see langword="null"/>,
    /// the edge is always active when a message is generated by the source.
    /// </summary>
    public PredicateT? Condition => condition;
}
