name: conditional-workflow
description: Demonstrates conditional branching based on user input

# Declare expected inputs with their types
inputs:
  age:
    type: integer
    description: The user's age in years

actions:
  # Get the age from input
  - kind: SetValue
    id: get_age
    displayName: Get user age
    path: Local.age
    value: =inputs.age

  # Determine age category using nested conditions
  - kind: If
    id: check_age
    displayName: Check age category
    condition: =Local.age < 13
    then:
      - kind: SetValue
        path: Local.category
        value: child
      - kind: SendActivity
        activity:
          text: "Welcome, young one! Here are some fun activities for kids."
    else:
      - kind: If
        condition: =Local.age < 20
        then:
          - kind: SetValue
            path: Local.category
            value: teenager
          - kind: SendActivity
            activity:
              text: "Hey there! Check out these cool things for teens."
        else:
          - kind: If
            condition: =Local.age < 65
            then:
              - kind: SetValue
                path: Local.category
                value: adult
              - kind: SendActivity
                activity:
                  text: "Welcome! Here are our professional services."
            else:
              - kind: SetValue
                path: Local.category
                value: senior
              - kind: SendActivity
                activity:
                  text: "Welcome! Enjoy our senior member benefits."

  # Send a summary
  - kind: SendActivity
    id: summary
    displayName: Send category summary
    activity:
      text: '=Concat("You have been categorized as: ", Local.category)'

  # Store result
  - kind: SetValue
    id: set_output
    path: Workflow.Outputs.category
    value: =Local.category
