#
# This workflow demonstrates a single agent interaction based on user input.
#
# Any Foundry Agent may be used to provide the response.
# See: ./setup/QuestionAgent.yaml
#
kind: Workflow
trigger:

  kind: OnConversationStart
  id: workflow_demo
  actions:

    - kind: InvokeAzureAgent
      id: invoke_analyst
      conversationId: =System.ConversationId
      agent:
        name: =Env.FOUNDRY_AGENT_ANSWER
      input:
        messages: =[UserMessage(System.LastMessageText)]
        additionalInstructions: |-
          You are a marketing analyst. Given a product description, identify:
          - Key features
          - Target audience
          - Unique selling points          

    - kind: InvokeAzureAgent
      id: invoke_writer
      conversationId: =System.ConversationId
      agent:
        name: =Env.FOUNDRY_AGENT_ANSWER
      input:
        additionalInstructions: |-
          You are a marketing copywriter. Given a block of text describing features, audience, and USPs,
          compose a compelling marketing copy (like a newsletter section) that highlights these points.
          Output should be short (around 150 words), output just the copy as a single text block.

    - kind: InvokeAzureAgent
      id: invoke_editor
      conversationId: =System.ConversationId
      agent:
        name: =Env.FOUNDRY_AGENT_ANSWER
      input:
        additionalInstructions: |-
          You are an editor. Given the draft copy, correct grammar, improve clarity, ensure consistent tone,
          give format and make it polished. Output the final improved copy as a single text block.